# Draft a Unified Table for **Points of Interest** in Berlin Layers

## Step 1: Gather info on tables already in the database

### Import libraries

In [1]:
# Import Libraries
import osmnx as ox # to fetch data from OpenStreetMap
import geopandas as gpd # to work with geospatial data
import pandas as pd
# import psycopg2
from sqlalchemy import create_engine, text
import warnings
import json

warnings.filterwarnings("ignore")

### Credentials

In [ ]:
user_name=''
password='f'

### Create the connection

In [3]:
# Conection
host = 'localhost'
port = '5433'
database = 'layereddb'
schema='berlin_source_data'

#connection to db after you opened tunnel
engine = create_engine(f'postgresql+psycopg2://{user_name}:{password}@{host}:{port}/{database}')

### Queries

- Show tables list that are not statitics

In [4]:
# Get all table names
query = """
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'berlin_source_data'
  AND table_type = 'BASE TABLE'
  AND table_name NOT ILIKE '%stat%'
"""
# Execute the query
poi_tables_df = pd.read_sql(text(query), engine)
print(poi_tables_df)

                          table_name
0                          galleries
1                            museums
2                           theaters
3                   pools_refactored
4                    public_artworks
5        theaters_backup_neigh_final
6          district_level_aggregated
7                              malls
8                     bus_tram_stops
9                            doctors
10                             banks
11           social_clubs_activities
12  veterinary_clinics_martin_svitek
13              hospitals_refactored
14                        pharmacies
15                        bike_lanes
16                      supermarkets
17                             pools
18                       land_prices
19          test_table_george_smelin
20                            venues
21                      post_offices
22                    dental_offices
23                         districts
24                              gyms
25               short_term_listings
26                long_term_listings
27                       night_clubs
28                           schools
29                     neighborhoods
30                      universities
31                         hospitals
32     milieuschutz_protection_zones
33                veterinary_clinics
34                             parks
35                             sbahn
36                     kindergartens
37                             ubahn
38                       playgrounds
39                exhibition_centers

- Show tables list that are only statitics

In [5]:
query = f"""
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'berlin_source_data'
    AND table_name LIKE '%stat%'
ORDER BY table_name;
"""

# Execute the query
stats_tables_df = pd.read_sql(text(query), engine)
print(stats_tables_df)

                    table_name
0             crime_statistics
1           districts_pop_stat
2          regional_statistics
3  rent_stats_per_neighborhood

In [6]:
# Loop through tables and show top 5 rows of stats tables
for table in stats_tables_df['table_name']:
    print(f"\n--- {table} ---")
    preview_query = f"SELECT * FROM berlin_source_data.{table} LIMIT 5;"
    df = pd.read_sql(text(preview_query), engine)
    display(df)

--- crime_statistics ---

,id,area_id,locality,district,district_id,year,crime_type_german,crime_type_english,category,total_number_cases,frequency_100k,population_base,severity_weight,created_at,updated_at
0,2001,13007.0,Osloer Straße,Mitte,11001001,2015,Brand- stiftung,Arson,Property Crime,13,34.0,None,4.5,2025-08-21 12:52:44.976746,2025-08-21 12:52:44.976746
1,2002,13008.0,Brunnenstraße Nord,Mitte,11001001,2015,Brand- stiftung,Arson,Property Crime,10,27.0,None,4.5,2025-08-21 12:52:44.976746,2025-08-21 12:52:44.976746
2,2003,14009.0,Parkviertel,Mitte,11001001,2015,Brand- stiftung,Arson,Property Crime,16,36.0,None,4.5,2025-08-21 12:52:44.976746,2025-08-21 12:52:44.976746
3,2004,14010.0,Wedding Zentrum,Mitte,11001001,2015,Brand- stiftung,Arson,Property Crime,14,25.0,None,4.5,2025-08-21 12:52:44.976746,2025-08-21 12:52:44.976746
4,2005,19900.0,"Bezirk (Mi), nicht zuzuordnen",Mitte,11001001,2015,Brand- stiftung,Arson,Property Crime,8,NaN,None,4.5,2025-08-21 12:52:44.976746,2025-08-21 12:52:44.976746

--- districts_pop_stat ---

,district_id,district,male,female,germans,foreigners,single,married,widowed,divorced,...,römisch_katholische_kirche,religion_other_or_none,0-6,6-15,15-18,18-27,27-45,45-55,55-65,65+
0,11001001,Mitte,204542,192462,249053,147951,240196,113277,13119,28623,...,28294,333248,20516,29120,9461,49247,145300,47278,44361,51721
1,11002002,Friedrichshain-Kreuzberg,150002,142622,202632,89992,188392,76076,7369,19227,...,17094,251355,14918,21510,6836,30281,114196,40160,32574,32149
2,11003003,Pankow,209773,217503,343105,84171,246687,130125,17014,31848,...,23544,363021,22768,38101,12347,39397,132140,62325,56884,63314
3,11004004,Charlottenburg-Wilmersdorf,166037,177463,249994,93506,176967,114706,17823,32281,...,31889,263824,15921,23364,7968,35224,94225,39648,47924,79226
4,11005005,Spandau,127361,131916,189914,69363,125965,93781,15779,23333,...,21050,198091,15354,24680,7873,26455,66010,29564,35687,53654

--- regional_statistics ---

,district_id,district,year,inhabitants,total_area_ha,share_forest_water_agriculture,forest_area_ha,water_area_ha,agriculture_area_ha,population_density_per_ha,number_of_residences,living_space_per_resident_m2
0,11004004,Charlottenburg-Wilmersdorf,2012,298567,6472,0.295,1622,281,794,46.1,184637,48.9
1,11002002,Friedrichshain-Kreuzberg,2012,259483,2034,0.067,4,132,1,127.6,145328,39.3
2,11011011,Lichtenberg,2012,258586,5212,0.140,51,104,293,49.6,143895,37.0
3,11010010,Marzahn-Hellersdorf,2012,248786,6178,0.060,173,117,573,40.3,127149,37.1
4,11001001,Mitte,2012,329969,3947,0.036,0,142,0,83.6,185209,39.2

--- rent_stats_per_neighborhood ---

,district_id,district,median_net_rent_per_m2,number_of_cases,mean_net_rent_per_m2,year
0,11001001,Mitte,19.91,4169,19.91,2024
1,11002002,Friedrichshain-Kreuzberg,19.42,2509,19.26,2024
2,11003003,Pankow,17.00,3636,17.65,2024
3,11004004,Charlottenburg-Wilmersdorf,19.39,3036,19.40,2024
4,11005005,Spandau,12.00,2403,13.32,2024

In [7]:
# Loop through tables and show top 5 rows of point of interest tables
for table in poi_tables_df['table_name']:
    print(f"\n--- {table} ---")
    preview_query = f"SELECT * FROM berlin_source_data.{table} LIMIT 5;"
    df = pd.read_sql(text(preview_query), engine)
    display(df)

--- galleries ---

,id,name,house_number,street,neighborhood_id,district_id,postal_code,website,opening_hours,wheelchair,fee,latitude,longitude
0,301107444,atelier achim kühn,6,richter straße,0908,11009009,12524,None,None,None,None,52.409750,13.571342
1,370766098,galerie zandi,57,mommsen straße,0401,11004004,10629,None,mo-fr 11:00-18:00; sa 11:00-16:00,no,false,52.503135,13.313631
2,410135935,studio für gestaltung,31,bürkner straße,0801,11008008,12047,None,"th,fr 13:00-18:00; sa 12:00-16:00",yes,false,52.493327,13.427490
3,410692505,la girafe,None,None,0202,11002002,None,None,None,no,false,52.492914,13.437057
4,410745800,kronenboden,16,schweden straße,0106,11001001,13357,None,None,yes,None,52.555091,13.375326

--- museums ---

,id,name,house_number,street,neighborhood_id,district_id,postal_code,website,normalized_phone,museum_type,operator,building,wikipedia,opening_hours,wheelchair,toilets_wheelchair_accessible,fee,latitude,longitude
0,73696610,gedenkstätte deutscher widerstand,13-14,stauffenberg straße,0104,11001001,10785,https://www.gdw-berlin.de/,None,None,None,None,de:gedenkstätte deutscher widerstand,mo-fr 09:00-18:00; sa-su 10:00-18:00,limited,None,false,52.507605,13.362986
1,84644782,"dokumentationszentrum flucht, vertreibung, ver...",90,stresemann straße,0202,11002002,10963,https://www.flucht-vertreibung-versoehnung.de/,None,None,None,None,"de:stiftung flucht, vertreibung, versöhnung",tu-su 10:00-19:00; mo off,yes,yes,false,52.504871,13.382214
2,259855486,berliner s-bahn-museum,3,koppen straße,0201,11002002,10243,https://s-bahn-museum.de/,None,railway,berliner s-bahn-museum ggmbh,None,None,"we 12:00-16:00, th,fr 15:00-20:00, su 14:00-18:00",yes,None,true,52.510475,13.432765
3,268591806,das museum der domäne dahlem,None,None,0605,11006006,None,https://www.domaene-dahlem.de/home/,None,open_air,None,None,None,mo-su 10:00-18:00; th off,limited,None,true,52.458357,13.288944
4,281391655,stasimuseum,103,rusche straße,1103,11011011,10365,https://www.stasimuseum.de/,+49 30 5536854,history,astak e.v.,None,de:forschungs- und gedenkstätte normannenstraße,mo-fr 10:00-18:00; sa-su 11:00-18:00,yes,None,true,52.514507,13.487485

--- theaters ---

,theater_id,name,name_key,place_type,operator,opening_hours,wheelchair,screen,website,phone,...,addr_country,theatre_tags,theatre_category,district_id,district,neighborhood_id,longitude,latitude,last_updated,neighborhood
0,thb_1fed95705f16,Filmrauschpalast,filmrauschpalast,cinema,Filmrausch Moabit e.V.,None,no,1,https://www.filmrausch.de/,+49303844344,...,DE,None,None,11001001,Mitte,0102,13.359623,52.534378,2025-10-12 23:39:15,Moabit
1,thb_957cf1213125,Friedrichstadt-Palast,friedrichstadt-palast,theatre,None,None,yes,0,https://www.palast.berlin/,+493023262326,...,DE,None,None,11001001,Mitte,0101,13.388879,52.523922,2025-10-12 23:39:15,Mitte
2,thb_e0da8d4b4612,Quatsch Comedy Club,quatsch-comedy-club,theatre,None,None,limited,0,https://www.quatsch-comedy-club.de/,+493027879030,...,DE,stand_up_comedy,stand_up_comedy,11001001,Mitte,0101,13.388621,52.523624,2025-10-12 23:39:15,Mitte
3,thb_68dcca1fbb44,Piano Salon Christophori,piano-salon-christophori,theatre,None,None,yes,0,https://www.konzertfluegel.com/,None,...,DE,chamber_music,concert_hall,11001001,Mitte,0106,13.373947,52.551597,2025-10-12 23:39:15,Gesundbrunnen
4,thb_620a00f98f4e,Il Kino,il,cinema,None,Mo-Su 14:00-22:00+,yes,0,https://ilkino.de/,+493062903878,...,DE,None,None,11008008,Neukölln,0801,13.433041,52.491664,2025-10-12 23:39:15,Neukölln

--- pools_refactored ---

,pool_id,name,pool_type,street,postal_code,latitude,longitude,open_all_year,district,district_id,neighborhood,neighborhood_id
0,472,Strandbad Lübars,Naturbad,Am Freibad 9,13469,52.61824,13.33519,False,Reinickendorf,11012012,Lübars,1208
1,473,Kleine Schwimmhalle Wuhlheide,Hallenbad,An der Wuhlheide 161,12459,52.45993,13.53965,True,Treptow-Köpenick,11009009,Oberschöneweide,0909
2,474,Kombibad Mariendorf,Kombibad,Ankogelweg 95,12107,52.41972,13.40154,True,Tempelhof-Schöneberg,11007007,Mariendorf,0704
3,475,Schwimmhalle Anton-Saefkow-Platz,Hallenbad,Anton-Saefkow-Platz 1,10369,52.53093,13.47184,True,Lichtenberg,11011011,Fennpfuhl,1111
4,476,Stadtbad Kreuzberg - Baerwaldbad,Hallenbad,Baerwaldstraße 64-67,10961,52.49451,13.40432,True,Friedrichshain-Kreuzberg,11002002,Kreuzberg,0202

--- public_artworks ---

,id,name,artwork_type,artist_name,street,neighborhood_id,district_id,postal_code,material,start_date,image,wikidata,wikimedia_commons,latitude,longitude
0,28341970,seepferdchen,sculpture,None,spreetunnel,0910,11009009,12559,metal,None,None,None,None,52.444170,13.625088
1,243487615,richard wagner,statue,None,tiergarten straße,0104,11001001,10785,None,None,https://photos.app.goo.gl/9vgmjzd9uthahjab8,Q2148898,None,52.510066,13.361869
2,255049659,flensburger löwe,statue,kopie nach hermann wilhelm bissen,tiefhorn weg,0607,11006006,14109,None,1938,None,Q105045191,category:flensburg lion (copy in berlin),52.433884,13.164987
3,258485628,begegnung,sculpture,jo doese,anton saefkow platz,1111,11011011,10369,stone,None,https://fennpfuhl.digital/img/statue/begegnung...,Q110311378,category:begegnung (joachim doese),52.528735,13.473156
4,262455591,reiterstandbild friedrich ii. von preußen,statue,christian daniel rauch,unter den linden,0101,11001001,10117,None,None,https://commons.wikimedia.org/wiki/file:berlin...,Q881611,category:reiterstandbild friedrichs des großen...,52.517260,13.392744

--- theaters_backup_neigh_final ---

,theater_id,name,name_key,place_type,operator,opening_hours,wheelchair,screen,website,phone,...,addr_country,theatre_tags,theatre_category,district_id,district,neighborhood_id,longitude,latitude,last_updated,neighborhood
0,thb_1fed95705f16,Filmrauschpalast,filmrauschpalast,cinema,Filmrausch Moabit e.V.,None,no,1,https://www.filmrausch.de/,+49303844344,...,DE,None,None,11001001,Mitte,102,13.359623,52.534378,2025-10-12 23:39:15,Moabit
1,thb_957cf1213125,Friedrichstadt-Palast,friedrichstadt-palast,theatre,None,None,yes,0,https://www.palast.berlin/,+493023262326,...,DE,None,None,11001001,Mitte,101,13.388879,52.523922,2025-10-12 23:39:15,Mitte
2,thb_e0da8d4b4612,Quatsch Comedy Club,quatsch-comedy-club,theatre,None,None,limited,0,https://www.quatsch-comedy-club.de/,+493027879030,...,DE,stand_up_comedy,stand_up_comedy,11001001,Mitte,101,13.388621,52.523624,2025-10-12 23:39:15,Mitte
3,thb_83a06ac56172,ACUDkino,acudkino,cinema,None,None,no,2,https://acudkino.de/,+493044359498,...,DE,None,None,11001001,Mitte,101,13.400815,52.533659,2025-10-12 23:39:15,Mitte
4,thb_089e4d79610a,Ballhaus Ost,ballhaus-ost,theatre,None,None,limited,0,https://www.ballhausost.de/,+493044049250,...,DE,None,None,11003003,Pankow,301,13.414978,52.543077,2025-10-12 23:39:15,Prenzlauer Berg

--- district_level_aggregated ---

,district_id,district,long_term_listings_count,avg_long_term_listings_price,median_long_term_listings_price,avg_long_term_listings_rooms,avg_long_term_listings_surface_sqm,rooms_1_count,rooms_1_5_count,rooms_2_count,...,latest_land_value_others_per_sqm,latest_land_value_residential_area_per_sqm,latest_mean_net_rent_sqm,protection_zones_count,total_area_em_ha,total_area_es_ha,dental_offices_count,dental_wheelchair_yes_count,dental_wheelchair_no_count,dental_wheelchair_limited_count
0,11001001,Mitte,175,2045.90,1750.0,2.33,79.35,39,3,59,...,9000.0,1600.0,19.91,32.0,686.6,658.4,82,18,16,8
1,11002002,Friedrichshain-Kreuzberg,105,1770.07,1714.0,2.39,69.51,16,1,43,...,15.0,3000.0,19.26,17.0,981.3,604.5,57,11,20,2
2,11003003,Pankow,154,1869.21,1724.5,2.78,81.77,21,3,47,...,10.0,2000.0,17.65,22.0,833.2,458.2,93,8,22,12
3,11004004,Charlottenburg-Wilmersdorf,130,1987.59,1612.5,2.58,80.97,24,0,44,...,10.0,1800.0,19.40,18.0,397.2,237.2,136,9,17,9
4,11005005,Spandau,104,1551.15,1584.5,3.07,90.78,6,3,31,...,40.0,40.0,13.32,3.0,205.4,57.7,16,1,4,0

--- malls ---

,id,name,website,opening_hours,street,housenumber,postcode,city,latitude,longitude,wheelchair,source,district,neighborhood,neighborhood_id,district_id
0,360009454,Cladow-Center,None,None,None,None,0,Berlin,52.455157,13.144413,Yes,Osm Overpass,Spandau,Kladow,506,11005005
1,2782835444,Nordmeile,None,Mo-Sa 07:00-21:00,Oraniendamm,6-10,13469,Berlin,52.607867,13.325992,None,Osm Overpass,Reinickendorf,Waidmannslust,1207,11012012
2,3982921774,Springpfuhl-Passage,None,None,None,None,0,Berlin,52.526728,13.540104,Yes,Osm Overpass,Marzahn-Hellersdorf,Marzahn,1001,11010010
3,5024078544,Fennpfuhl-Karree,None,24/7,None,None,0,Berlin,52.528781,13.471797,Yes,Osm Overpass,Lichtenberg,Fennpfuhl,1111,11011011
4,10632546,Hallen Am Borsigturm,Http://Www.Hab-2.De,Mo-Sa 10:00-20:00,Am Borsigturm,2,13507,Berlin,52.584576,13.285772,Yes,Osm Overpass,Reinickendorf,Tegel,1202,11012012

--- bus_tram_stops ---

,stop_id,district_id,name,address,latitude,longitude,neighborhood,district
0,900086106,11012012,Auguste-Viktoria-A./Humboldtstr. (Berlin),"Ollenhauerstraße 24, 13403 Berlin, Germany",52.568845,13.329852,Borsigwalde,Reinickendorf
1,900170515,11010010,Adersleber Weg (Berlin),"Adersleber Weg, 12685 Berlin, Germany",52.537896,13.560318,Marzahn,Marzahn-Hellersdorf
2,900151501,11011011,Ahrenshooper Str. (Berlin),"Ahrenshooper Str., 13051 Berlin, Germany",52.566212,13.501888,Alt-Hohenschönhausen,Lichtenberg
3,900140005,11003003,Albertinenstr. (Berlin),"Berlin, Albertinenstr., 13088 Berlin, Germany",52.549788,13.457778,Stadtrandsiedlung Malchow,Pankow
4,900161517,11011011,Alfred-Kowalke-Str. (Berlin),"Alfred-Kowalke-Straße, 10319 Berlin, Germany",52.505714,13.519704,Friedrichsfelde,Lichtenberg

--- doctors ---

,id,district_id,neighborhood_id,name,street,housenumber,city,postcode,amenity,speciality,opening_hours,website,longitude,latitude,wheelchair,description,email,toilets_wheelchair,wheelchair_description
0,7823742547,11001001,101,A-Arbeitsmedizin,Schwartzkopffstraße,15,Berlin,10115,practice,occupational,None,https://a-arbeitsmedizin.de/,13.379949,52.535000,None,None,info@a-arbeitsmedizin.de,None,None
1,11108705050,11003003,301,A. Dorosti Nadali,Dunckerstraße,17,Berlin,10437,practice,general,"Mo,Tu,Th 08:00-18:00; We 08:00-13:00",https://www.praxis-nadali.de/,13.421853,52.543434,None,None,None,None,None
2,4513645689,11002002,201,AID Friedrichshain,Frankfurter Allee,100,Berlin,None,practice,None,Mo-Fr 09:00-13:00; Sa 10:00-12:00; PH off,https://drogennotdienst.de/angebote/substituti...,13.472960,52.513693,yes,Substitution und Psychosoziale Betreuung (PSB),friedrichshain@notdienstberlin.de,None,None
3,7844240263,11004004,402,AL Urologie am Rüdesheimer Platz,Homburger Straße,16,Berlin,14197,practice,urology,"Mo 09:00-13:00,15:00-19:00; Tu 09:00-13:00; We...",https://www.al-urologie.de/,13.314986,52.474366,None,None,None,None,None
4,1930491527,11009009,907,ARZ,Albert-Einstein-Straße,4,Berlin,12489,practice,None,Mo-Fr 07:30-22:00; Sa 09:00-17:00,None,13.536666,52.431386,yes,None,None,None,None

--- banks ---

,bank_id,name,brand,operator,street,housenumber,postcode,opening_hours,atm,wheelchair,latitude,longitude,district,district_id
0,28968292,berliner volksbank,berliner volksbank,nan,berliner straße,42,10713,"mo-fr 10:00-13:00, mo 14:00-16:00, tu,th 14:00...",true,true,52.486668,13.319723,Charlottenburg-Wilmersdorf,11004004
1,60848455,sparkasse,nan,berliner sparkasse,anton-saefkow-platz,13,10369,"mo,we,fr 09:30-15:00; tu,th 09:30-18:00",true,unknown,52.530331,13.471037,Lichtenberg,11011011
2,87040399,dkb,nan,nan,nan,nan,nan,unknown,unknown,unknown,52.511050,13.388798,Mitte,11001001
3,89274635,deutsche bank,deutsche bank,deutsche bank,alexanderstraße,5,10178,mo-tu 10:00-18:00; we 10:00-16:00; th 10:00-18...,true,true,52.523238,13.415750,Mitte,11001001
4,203561614,sparkasse,nan,berliner sparkasse,helene-weigel-platz,1/2,12681,"mo,we,fr 09:30-15:00; tu,th 09:30-18:00",true,true,52.527687,13.538327,Marzahn-Hellersdorf,11010010

--- social_clubs_activities ---

,club_id,name,club,leisure,sport,amenity,street,housenumber,postcode,website,...,opening_hours,wheelchair,latitude,longitude,district,neighborhood_id,neighborhood,full_address,district_id,geometry
0,30012753,Umspannwerk,None,None,None,events_venue,None,None,None,None,...,unknown,true,52.494043,13.429187,Friedrichshain-Kreuzberg,0202,Kreuzberg,"Umspannwerk, Ohlauer Straße, Luisenstadt, Kreu...",11002002,POINT (13.4291868 52.4940425)
1,60775321,KW76,poker,None,None,None,Konrad-Wolf-Straße,76,None,None,...,unknown,unknown,52.538623,13.481623,Lichtenberg,1110,Alt-Hohenschönhausen,"KW76, 76, Konrad-Wolf-Straße, Wilhelmsberg, Al...",11011011,POINT (13.4816226 52.5386233)
2,257709121,Kulturhaus Spandau,None,None,None,arts_centre,None,None,None,None,...,unknown,true,52.535479,13.202312,Spandau,0501,Spandau,"Kulturhaus Spandau, Mauerstraße, Altstadt, Spa...",11005005,POINT (13.2023117 52.5354787)
3,266630320,Buergeramt Mahlsdorf,None,None,None,community_centre,Hönower Straße,91,12623,None,...,unknown,true,52.513140,13.612063,Marzahn-Hellersdorf,1004,Mahlsdorf,"Buergeramt Mahlsdorf, 91, Hönower Straße, Lich...",11010010,POINT (13.6120626 52.51314)
4,268915262,Karame e.V.,None,None,None,community_centre,Wilhelmshavener Straße,22,10551,None,...,"mo-fr 13:00-18:00; sa-su,ph off",false,52.531003,13.341544,Mitte,0102,Moabit,"Karame e.V., 22, Wilhelmshavener Straße, Alt-M...",11001001,POINT (13.3415438 52.5310025)

--- veterinary_clinics_martin_svitek ---

,clinic_id,clinic_name,amenity,street,house_number,postcode,city,phone_number,website,email,...,emergency,latitude,longitude,district_id,neighbourhood_id,full_address,district_id.1,district,neighbourhood_id.1,neighbourhood
0,268917040,Tierarztpraxis am Urban,veterinary,Baerwaldstraße,69,10961.0,Berlin,None,None,None,...,None,52.495684,13.405233,2,27,"Baerwaldstraße 69, 10961.0 Berlin",2,Friedrichshain-Kreuzberg,27,Kreuzberg
1,299795048,Dr. med. vet. Elke Hartwig,veterinary,Straße 48,67,13125.0,Berlin,+49 30 9437820,http://www.tierarztpraxis-hartwig.de/,None,...,None,52.606286,13.479555,7,24,"Straße 48 67, 13125.0 Berlin",7,Pankow,24,Karow
2,347294456,Tierarztpraxis Dr. Bernhard Sörensen,veterinary,Königsberger Straße,36,12207.0,Berlin,+49 30 7738321,https://www.tierarztpraxis-soerensen.de/,None,...,None,52.429722,13.320133,10,32,"Königsberger Straße 36, 12207.0 Berlin",10,Steglitz-Zehlendorf,32,Lichterfelde
3,394867279,Tierarztpraxis Jeanette Koepsel,veterinary,None,None,NaN,Berlin,None,None,None,...,None,52.535199,13.270573,9,52,Berlin,9,Spandau,52,Siemensstadt
4,411550894,Kleintierarztpraxis Berlin Kaulsdorf,veterinary,Planitzstraße,19,12621.0,Berlin,+49 30 53018585,https://www.tierarzt-kaulsdorf.de/,info@tierarzt-kaulsdorf.de,...,None,52.509511,13.589635,4,25,"Planitzstraße 19, 12621.0 Berlin",4,Marzahn-Hellersdorf,25,Kaulsdorf

--- hospitals_refactored ---

,hospital_id,district_id,name,operator,country,city,street,housenumber,postcode,neighborhood,...,emergency,speciality,opening_hours,latitude,longitude,geometry,source,amenity_tag,healthcare_tag,district
0,669088712,11009009,Ärztehaus Johannisthal,unknown,DE,Berlin,Sterndamm,152,12487,Johannisthal,...,unknown,unknown,unknown,52.439692,13.500167,POINT (13.5001666 52.4396916),OSM,clinic,clinic,Treptow-Köpenick
1,694302689,11011011,Ärztehaus am Roedeliusplatz,unknown,DE,Berlin,Schottstraße,4,10365,Lichtenberg,...,unknown,unknown,unknown,52.515142,13.490941,POINT (13.4909414 52.5151416),OSM,clinic,clinic,Lichtenberg
2,872223518,11002002,Ärztehaus,unknown,unknown,unknown,unknown,unknown,unknown,Kreuzberg,...,unknown,unknown,"Mo,Tu,Th 08:30-13:00,14:00-18:00; We,Fr 08:30-...",52.498845,13.419860,POINT (13.4198597 52.4988453),OSM,clinic,clinic,Friedrichshain-Kreuzberg
3,874357625,11002002,MVZ am Moritzplatz,unknown,DE,Berlin,Oranienstraße,158,10969,Kreuzberg,...,unknown,surgery;general,"Mo,Tu,Th 08:00-18:00; We,Fr 08:00-12:00",52.502792,13.413297,POINT (13.4132967 52.5027923),OSM,clinic,clinic,Friedrichshain-Kreuzberg
4,911925361,11003003,Ärztehaus Damerowstraße,unknown,DE,Berlin,Damerowstraße,7,13187,Pankow,...,unknown,unknown,unknown,52.572145,13.416976,POINT (13.4169764 52.5721447),OSM,clinic,clinic,Pankow

--- pharmacies ---

,pharmacy_id,district_id,name,street,housenumber,postal_code,phone_number,openinghours,website,coordinates,latitude,longitude,neighborhood,district,services_offered,wheelchair_accessible
0,60775323,11011011,reichenberger apotheke,reichenberger straße,3,13055.0,49309713807.0,mo-th 08:00-19:00; fr 08:00-18:30; sa 09:00-13:00,https://reichenbergerapotheke.de/,POINT(13.4866016 52.5407412),52.540741,13.486602,Alt-Hohenschönhausen,Lichtenberg,dispensing_yes,yes
1,60848447,11011011,castello-apotheke,None,None,None,None,mo-fr 08:30-19:00; sa 08:30-14:00,None,POINT(13.4696536 52.5318353),52.531835,13.469654,Fennpfuhl,Lichtenberg,dispensing_yes,yes
2,60852928,11011011,rosen apotheke,rudolf-seiffert-straße,11,10369.0,49309759449.0,mo-fr 08:00-19:00; sa 08:00-12:00,https://www.zurrose.de/,POINT(13.4685134 52.5275552),52.527555,13.468513,Fennpfuhl,Lichtenberg,dispensing_yes,yes
3,68437791,11009009,margareten-apotheke,karl-kunger-straße,46,12435.0,49305337855.0,mo-fr 08:30-18:30; sa 08:30-13:00,http://www.apotheke.borchert-online.de/,POINT(13.4505704 52.4893898),52.489390,13.450570,Alt-Treptow,Treptow-Köpenick,dispensing_yes,no
4,69226035,11001001,leipziger apotheke,leipziger straße,43,10117.0,None,mo-fr 08:00-19:00; sa 08:00-14:00,https://www.leipziger-apotheke.de/,POINT(13.3958628 52.5105561),52.510556,13.395863,Mitte,Mitte,dispensing_yes,yes

--- bike_lanes ---

,bikelane_id,street_name,district_id,district,neighborhood_id,neighborhood,length_m,geometry
0,way/43998936,Fritz-Lang-Platz,11010010,Marzahn-Hellersdorf,1005,Hellersdorf,163.576194,0105000020E61000000100000001020000000C00000014...
1,way/517805554,Sonnenallee,11008008,Neukölln,801,Neukölln,54.172358,0105000020E6100000010000000102000000080000007A...
2,way/1186003574,Am Nordgraben,11012012,Reinickendorf,1201,Reinickendorf,27.333073,0105000020E6100000010000000102000000110000008C...
3,way/1186011275,Am Nordgraben,11012012,Reinickendorf,1201,Reinickendorf,23.719633,0105000020E610000001000000010200000011000000EA...
4,way/1187324842,Sonnenallee,11008008,Neukölln,801,Neukölln,8.659062,0105000020E610000001000000010200000007000000AA...

--- supermarkets ---

,store_id,store_name,street,housenumber,postcode,city,opening_hours,brand,type,payment_credit_card,...,phone,email,website,latitude,longitude,source,district,neighborhood,neighborhood_id,district_id
0,58489979,netto marken-discount,alte jakobstraße,83,10179,berlin,mo-sa 07:00-24:00; su off,netto marken-discount,unknown,unknown,...,not_provided,not_provided,https://www.netto-online.de/filialen/berlin-mi...,52.509819,13.407373,osm,mitte,mitte,101,11001001
1,79418658,ledo,quäkerstraße,2,13403,berlin,mo-sa 09:00-20:00,independent,unknown,unknown,...,not_provided,not_provided,https://www.ledo-supermarkt.de/,52.572417,13.308547,osm,reinickendorf,reinickendorf,1201,11012012
2,79422426,kiezmarkt,Auguste-Viktoria-Allee,unknown,13403,Berlin,"mo-fr 08:00-20:00, sa 08:00-19:00",nahkauf,unknown,unknown,...,not_provided,not_provided,not_provided,52.571676,13.312476,osm,reinickendorf,reinickendorf,1201,11012012
3,79428988,nah & gut,scharnweberstraße,100,13405,berlin,mo-sa 07:00-22:00,edeka,unknown,unknown,...,+49 30 41199655,not_provided,not_provided,52.566403,13.316931,osm,reinickendorf,reinickendorf,1201,11012012
4,79438509,nahkauf,meller bogen,2,13403,berlin,mo-sa 07:00-20:00,nahkauf,unknown,unknown,...,030-346491610,not_provided,https://www.nahkauf.de/maerkte/berlin-42613025...,52.570486,13.321144,osm,reinickendorf,reinickendorf,1201,11012012

--- pools ---

,pool_id,district_id,name,pool_type,street,postal_code,latitude,longitude,open_all_year
0,472,11012012,Strandbad Lübars,Naturbad,Am Freibad 9,13469,52.61824,13.33519,False
1,473,11009009,Kleine Schwimmhalle Wuhlheide,Hallenbad,An der Wuhlheide 161,12459,52.45993,13.53965,True
2,474,11008008,Kombibad Mariendorf,Kombibad,Ankogelweg 95,12107,52.41972,13.40154,True
3,475,11011011,Schwimmhalle Anton-Saefkow-Platz,Hallenbad,Anton-Saefkow-Platz 1,10369,52.53093,13.47184,True
4,476,11002002,Stadtbad Kreuzberg - Baerwaldbad,Hallenbad,Baerwaldstraße 64-67,10961,52.49451,13.40432,True

--- land_prices ---

,district,standard_land_value_per_sqm,typical_land_use_type,typical_floor_space_ratio,land_use_category,district_id,year
0,Friedrichshain-Kreuzberg,400.0,W - Wohngebiet,0.025,Residential Area,11002002,2012
1,Reinickendorf,550.0,M2 - Mischgebiet,0.020,Mixed Area,11012012,2012
2,Friedrichshain-Kreuzberg,650.0,M2 - Mischgebiet,0.030,Mixed Area,11002002,2012
3,Tempelhof-Schöneberg,1300.0,M2 - Mischgebiet,0.030,Mixed Area,11007007,2012
4,Spandau,180.0,G - Gewerbe,NaN,Commercial Area,11005005,2012

--- test_table_george_smelin ---

   id     name  score
0   1    Alice     95
1   2      Bob     87
2   3  Charlie     78

--- venues ---

,venue_id,district_id,name,district,category,cuisine,phone,address,latitude,longitude,website,opening_hours_dict,opening_hours,postal_code,neighborhood,takeaway,wheelchair_accessible,operating_hours_category
0,V4322,11003003,Anton-Cafe-Bar,Pankow,bar,None,None,Berliner Allee 39,52.548581,13.451417,None,None,None,None,Weißensee,None,yes,No Data
1,V4458,11001001,May Café,Mitte,cafe,None,None,Chausseestraße 21,52.530437,13.383494,None,None,None,None,Mitte,None,None,No Data
2,V4459,11001001,Moccachino,Mitte,restaurant,None,None,"Müllerstraße 44/45, 13349 Berlin",52.551334,13.351045,None,None,None,13349.0,Wedding,None,yes,No Data
3,V4460,11001001,Çarik Kuruyemiş & Cafe,Mitte,cafe,None,None,"Müllerstraße 39, 13353 Berlin",52.549807,13.353569,None,None,None,13353.0,Wedding,None,limited,No Data
4,V4461,11001001,Hung Anh,Mitte,restaurant,vietnamese;sushi,None,"Chausseestraße 130, 10115 Berlin",52.527619,13.386323,None,"{'Fr': [['11:30', '23:00']], 'Mo': [['11:30', ...","Mo-Fr 11:30-23:00; PH,Sa,Su 12:00-23:00",10115.0,Mitte,None,no,Evening (9pm-11pm)

--- post_offices ---

,id,district_id,neighborhood_id,zip_code,city,street,house_no,location_type,location_name,closure_periods,opening_hours,latitude,longitude
0,4340626,11001001,101,10178,Berlin,Spandauer Str.,2,RETAIL_OUTLET,City Shop,[],Mo: 08:00-18:00; Tu: 08:00-18:00; We: 08:00-18...,52.521145,13.403767
1,6730,11001001,101,10178,Berlin,Rathausstr.,5,POSTBANK_FINANCE_CENTER,Postbank Filiale,"[{'type': 'closure', 'fromDate': '2025-10-29T0...",Mo: 09:30-18:30; Tu: 09:30-18:30; We: 09:30-18...,52.519737,13.411517
2,4307374,11001001,101,10178,Berlin,Karl-Liebknecht-Str.,13,RETAIL_OUTLET,Lotto Post Tabak,[],Mo: 08:00-19:00; Tu: 08:00-19:00; We: 08:00-19...,52.522327,13.408074
3,4125530,11001001,101,10179,Berlin,Grunerstr.,20,RETAIL_OUTLET,"GECO im ALEXA, Untergeschoss/Baseme",[],Mo: 09:00-19:45; Tu: 09:00-19:45; We: 09:00-19...,52.518764,13.416384
4,4326999,11001001,101,10179,Berlin,Brückenstr.,1a,RETAIL_OUTLET,Lotto-Post-Schreibwaren,[],Mo: 09:00-19:00; Tu: 09:00-19:00; We: 09:00-19...,52.511505,13.416914

--- dental_offices ---

,osm_id,osm_type,name,street,housenumber,postcode,city,opening_hours,wheelchair,phone,email,website,lat,lon,district_id
0,304183504,node,None,Hönower Straße,75,12623,Berlin,None,None,None,None,None,52.511410,13.612096,11010010
1,313539258,node,Zahnzentrum Wedding,Müllerstraße,34a,13353,Berlin,Mo 09:00-19:00; Tu 09:00-18:00; We 09:00-17:00...,yes,None,None,None,52.548840,13.355306,11001001
2,325161442,node,A. Nejad,None,None,<NA>,Berlin,Mo-Tu 09:00-19:00; We 09:00-14:00; Th 09:00-19...,yes,+49303619106,None,None,52.508842,13.180477,11005005
3,345236220,node,Dr. Beate Lengert,Kurfürstendamm,218,10719,Berlin,None,None,None,None,http://www.dr-beate-lengert.de/,52.502720,13.328136,11004004
4,391394177,node,Serpil Hartfiel,Kollwitzstraße,77,10435,Berlin,"Mo,Tu,Th 08:00-19:00; We 18:00-18:00; Fr 08:00...",no,None,None,None,52.537548,13.418994,11003003

--- districts ---

,district_id,district,geometry
0,11012012,Reinickendorf,0106000020E61000000100000001030000000100000084...
1,11004004,Charlottenburg-Wilmersdorf,0106000020E6100000010000000103000000010000000D...
2,11009009,Treptow-Köpenick,0106000020E610000001000000010300000001000000E9...
3,11003003,Pankow,0106000020E61000000400000001030000000100000012...
4,11008008,Neukölln,0106000020E610000001000000010300000001000000BF...

--- gyms ---

,gym_id,district_id,name,address,postal_code,phone_number,email,coordinates,latitude,longitude,neighborhood,district,geom
0,277958275,11012012,Kieser Training,Holzhauser Straße 140d,13509,+49 30 41718917,berlin5@kieser-training.com,POINT (13.3117903 52.5846088),52.584609,13.311790,1211,Reinickendorf,0101000020E61000008F705AF0A29F2A4040F9BB77D44A...
1,277958277,11003003,Kieser Training,Ostseestraße 107,10409,+49 30 42105260,berlin6@kieser-training.com,POINT (13.4425034 52.5467638),52.546764,13.442503,301,Pankow,0101000020E610000087C3D2C08FE22A40A950DD5CFC45...
2,277958288,11004004,Kieser Training,Forckenbeckstraße 9-13,14199,None,None,POINT (13.3051873 52.4799991),52.479999,13.305187,403,Charlottenburg-Wilmersdorf,0101000020E610000026547078419C2A406D8E739B703D...
3,277958289,11006006,Kieser Training,Teltowkanalstraße 2,12247,None,None,POINT (13.3296947 52.4429012),52.442901,13.329695,603,Steglitz-Zehlendorf,0101000020E6100000374F75C8CDA82A40CF2EDFFAB038...
4,277958291,11008008,Kieser Training,Rudower Straße 132,12351,None,None,POINT (13.4690013 52.4339942),52.433994,13.469001,803,Neukölln,0101000020E6100000259529E620F02A4082548A1D8D37...

--- short_term_listings ---

,district_id,district,id,host_id,neighborhood,latitude,longitude,property_type,room_type,accommodates,...,maximum_nights,number_of_reviews,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month
0,11003003,Pankow,3176,3718,Prenzlauer Berg Südwest,52.53471,13.41810,Entire rental unit,Entire home/apt,2,...,730,149,4.63,4.67,4.52,4.65,4.70,4.92,4.61,0.76
1,11003003,Pankow,9991,33852,Prenzlauer Berg Südwest,52.53269,13.41805,Entire rental unit,Entire home/apt,7,...,14,7,5.00,5.00,5.00,5.00,5.00,4.86,4.86,0.06
2,11003003,Pankow,14325,55531,Prenzlauer Berg Nordwest,52.54813,13.40366,Entire rental unit,Entire home/apt,1,...,1125,26,4.68,5.00,4.85,4.70,4.85,4.60,4.45,0.14
3,11002002,Friedrichshain-Kreuzberg,16644,64696,nördliche Luisenstadt,52.50312,13.43508,Entire condo,Entire home/apt,4,...,365,48,4.72,4.86,4.86,4.93,4.86,4.67,4.71,0.26
4,11008008,Neukölln,17904,68997,Reuterstraße,52.49419,13.42166,Entire rental unit,Entire home/apt,2,...,365,298,4.77,4.82,4.71,4.89,4.92,4.88,4.65,1.60

--- long_term_listings ---

,listing_id,detail_url,raw_info,type,first_tenant,price_euro,number_of_rooms,surface_m2,floor,street,house_number,neighborhood,district,postal_code,city,address,latitude,longitude,geometry,district_id
0,WOH_2772_178_14055,https://www.immowelt.de/expose/fb32adca-5d67-4...,Wohnung zur Miete 2.772 € 4 Zimmer 178 m² frei...,Wohnung,no,2772,4.0,178.0,NaN,Stallupöner Allee,33,Westend,Charlottenburg-Wilmersdorf,14055,Berlin,Stallupöner Allee 33 14055 Westend Berlin,52.504417,13.234717,POINT (13.234717 52.504417),11004004
1,STU_495_43_13627,https://www.immowelt.de/expose/4985f014-94b9-4...,"Studio zur Miete 495 € 2 Zimmer 43,7 m² frei a...",Studio,no,495,2.0,43.7,NaN,Schweiggerweg,5,Charlottenburg-Nord,Charlottenburg-Wilmersdorf,13627,Berlin,Schweiggerweg 5 13627 Charlottenburg Berlin,52.538645,13.282277,POINT (13.2822767 52.5386453),11004004
2,STU_1625_44_10717,https://www.immowelt.de/expose/2144d17c-ae55-4...,Studio zur Miete 1.625 € 2 Zimmer 44 m² EG Gün...,Studio,no,1625,2.0,44.0,0.0,Güntzelstr,32,Wilmersdorf,Charlottenburg-Wilmersdorf,10717,Berlin,Güntzelstr 32 10717 Wilmersdorf Berlin,52.492051,13.320604,POINT (13.3206041 52.4920513),11004004
3,WOH_2400_132_14050,https://www.immowelt.de/expose/8d048a9f-4bf4-4...,Wohnung zur Miete 2.400 € 3 Zimmer 132 m² Dach...,Wohnung,no,2400,3.0,132.0,2.0,None,None,Westend,Charlottenburg-Wilmersdorf,14050,Berlin,14050 Westend Berlin,52.520175,13.269123,POINT (13.2691228 52.5201745),11004004
4,WOH_1200_45_10589,https://www.immowelt.de/expose/25ne5mmgni7e?ln...,Wohnung zur Miete 1.200 € 2 Zimmer 45 m² 5 Ges...,Wohnung,no,1200,2.0,45.0,5.0,Kamminer Straße,4,Charlottenburg,Charlottenburg-Wilmersdorf,10589,Berlin,Kamminer Straße 4 10589 Charlottenburg Berlin,52.524411,13.300144,POINT (13.3001437 52.5244114),11004004

--- night_clubs ---

,id,district_id,neighborhood_id,club_name,city,postcode,street,house_num,phone,email,website,opening_hours,wheelchair,toilets_wheelchair,wheelchair_description,live_music,longitude,latitude
0,way/23278633,11001001,101,Roadrunners Rock & Motor Club,Berlin,10117,Unter den Linden,None,+49 30 78082991,None,http://www.roadrunners-paradise.de,None,limited,None,None,None,13.395131,52.517389
1,way/24248500,11001001,101,Werk9,Berlin,10117,Unter den Linden,None,+49 30 20165823,info@werk9.de,https://www.werk9.de/,None,limited,yes,"Haben für den Eingang eine Rampe, die muss bei...",None,13.395131,52.517389
2,way/24283864,11002002,201,Pride Warehouse,Berlin,10247,Colbestraße,26,None,None,None,None,limited,None,None,None,13.463285,52.512310
3,way/36908987,11002002,202,Gretchen,Berlin,10963,Obentrautstraße,19-21,+49 30 25922702,gretchen@gretchen-club.de,https://www.gretchen-club.de/,"""Je nach Veranstaltung""",yes,None,None,None,13.387921,52.495564
4,way/41474936,11003003,301,Duncker,Berlin,10439,Dunckerstraße,64,+49 30 4459509,None,https://www.dunckerclub.de/,Mo 22:00-04:00; Fr-Sa 22:00-05:00; Su 12:00-19:00,yes,no,None,None,13.422776,52.546894

--- schools ---

,id,bsn,school_name,school_type_de,ownership_en,school_category_de,school_category_en,district_id,district,quarter,...,school_year,students_total,students_f,students_m,teachers_total,teachers_f,teachers_m,startchancen_flag,longitude,latitude
0,1,01A04,Berlin-Kolleg,Kolleg,Public,Andere Schule,Other School,11001001,Mitte,Moabit,...,2024/25,NaN,NaN,NaN,NaN,NaN,NaN,False,13.334,52.527
1,2,01B01,"OSZ Banken, Immobilien und Versicherungen",Oberstufenzentrum,Public,Berufsschule,Vocational School,11001001,Mitte,Moabit,...,2024/25,1603.0,642.0,961.0,76.0,41.0,35.0,False,13.358,52.524
2,3,01B02,Staatliche Technikerschule Berlin,Fachschule,Public,Berufsschule,Vocational School,11001001,Mitte,Moabit,...,2024/25,480.0,56.0,424.0,57.0,25.0,32.0,False,13.338,52.523
3,4,01B03,"OSZ Kommunikations-, Informations- und Medient...",Oberstufenzentrum,Public,Berufsschule,Vocational School,11001001,Mitte,Gesundbrunnen,...,2024/25,1226.0,310.0,916.0,82.0,40.0,42.0,True,13.380,52.557
4,5,01B04,OSZ Gesundheit I,Oberstufenzentrum,Public,Berufsschule,Vocational School,11001001,Mitte,Wedding,...,2024/25,2902.0,2564.0,338.0,94.0,65.0,29.0,False,13.353,52.558

--- neighborhoods ---

,district_id,district,neighborhood_id,neighborhood,geometry
0,11001001,Mitte,0101,Mitte,0106000020E61000000100000001030000000100000006...
1,11001001,Mitte,0102,Moabit,0106000020E61000000100000001030000000100000002...
2,11001001,Mitte,0103,Hansaviertel,0106000020E61000000100000001030000000100000006...
3,11001001,Mitte,0104,Tiergarten,0106000020E61000000100000001030000000100000055...
4,11001001,Mitte,0105,Wedding,0106000020E6100000010000000103000000010000004E...

--- universities ---

,university_id,university_name,rank_in_berlin_brandenburg,rank_in_germany,enrollment,founded,latitude,longitude,postcode,district,district_id,neighborhood
0,1,Free University of Berlin,1,5,37908,1948,52.454324,13.293477,14195,Steglitz-Zehlendorf,11006006,Dahlem
1,2,Humboldt University of Berlin,2,8,36232,1809,52.517883,13.393655,10117,Mitte,11001001,Mitte
2,3,Technical University of Berlin,3,19,34842,1946,52.512532,13.326945,10623,Charlottenburg-Wilmersdorf,11004004,Charlottenburg
3,4,Charite - Medical University of Berlin,4,21,9340,1710,52.469383,13.311426,14197,Charlottenburg-Wilmersdorf,11004004,Wilmersdorf
4,5,Berlin University of Applied Sciences,7,84,14167,1994,52.515796,13.328141,10587,Charlottenburg-Wilmersdorf,11004004,Charlottenburg

--- hospitals ---

,district_id,name,address,coordinates,latitude,longitude,locality,district,distance,beds,cases
0,11001001,St. Hedwig-Krankenhaus Berlin,Große Hamburger Straße 5-11\n10115 Berlin,"52.52582662684028, 13.396515830691005",52.525827,13.396516,Alexanderplatz,Mitte,0.8,427,64515
1,11001001,Charité - Universitätsmedizin Berlin,Charitéplatz 1\n10117 Berlin,"52.52662465412624, 13.376658301525385",52.526625,13.376658,Alexanderplatz,Mitte,2.2,3011,1891343
2,11002002,Vivantes Klinikum im Friedrichshain,Landsberger Allee 49\n10249 Berlin,"52.52476641204036, 13.43904818247062",52.524766,13.439048,Karl-Marx-Allee-Nord,Friedrichshain-Kreuzberg,2.4,956,111119
3,11003003,Psychiatrisch-Psychotherapeutische Tagesklinik...,Diesterwegstr. 32\n10405 Berlin,"52.5413743809574, 13.430949",52.541374,13.430949,Prenzlauer Berg Süd,Pankow,2.7,21,2004
4,11002002,Vivantes Klinikum Am Urban,Dieffenbachstraße 1\n10967 Berlin,"52.494275898889505, 13.40892918516296",52.494276,13.408929,Tempelhofer Vorstadt,Friedrichshain-Kreuzberg,2.9,607,65066

--- milieuschutz_protection_zones ---

,protection_zone_id,protection_zone_key,protection_zone_name,district,district_id,date_announced,date_effective,amendment_announced,amendment_effective,area_ha,zone_type,geometry
0,erhaltgeb_em.EM0105,EM0105,Sparrplatz,Mitte,11001001,2016-05-24,2016-05-25,None,None,51.3,EM,0106000020E6100000010000000103000000010000002D...
1,erhaltgeb_em.EM0106,EM0106,Leopoldplatz,Mitte,11001001,2016-05-24,2016-05-25,None,None,62.1,EM,0106000020E61000000100000001030000000100000030...
2,erhaltgeb_em.EM0107,EM0107,Waldstraße,Mitte,11001001,2016-05-24,2016-05-25,None,None,72.6,EM,0106000020E6100000010000000103000000010000002C...
3,erhaltgeb_em.EM0108,EM0108,Birkenstraße,Mitte,11001001,2016-05-24,2016-05-25,None,None,81.6,EM,0106000020E61000000100000001030000000100000068...
4,erhaltgeb_em.EM0109,EM0109,Seestraße,Mitte,11001001,2016-05-24,2016-05-25,None,None,48.6,EM,0106000020E61000000100000001030000000100000013...

--- veterinary_clinics ---

Empty DataFrame
Columns: [clinic_id, clinic_name, street, house_number, postcode, city, district_id, neighbourhood_id, phone_number, website, email, opening_hours, operator, speciality, wheelchair_acces, full_address, pt_geom, footprint_geom]
Index: []

--- parks ---

,park_id,name,latitude,longitude,district,district_id,neighborhood,neighborhood_id,full_address,area_sq_m
0,4413796,Preußenpark,52.492540,13.312507,Charlottenburg-Wilmersdorf,11004004,Wilmersdorf,0402,"Brandenburgische Straße, Wilmersdorf, Charlott...",52609.724320
1,4440110,Unknown,52.398937,13.394560,Tempelhof-Schöneberg,11007007,Lichtenrade,0706,"23E, Simpsonweg, John-Locke-Siedlung, Lichtenr...",6213.374569
2,4592869,Ottopark,52.525604,13.337075,Mitte,11001001,Moabit,0102,"Spielplatz Ottopark, 34, Alt-Moabit, Moabit, M...",19600.760712
3,4611881,Mendelssohn-Bartholdy-Park,52.502937,13.376685,Friedrichshain-Kreuzberg,11002002,Kreuzberg,0202,"Schöneberger Straße, Kreuzberg, Friedrichshain...",19899.627180
4,4638994,Viktoriapark,52.487465,13.380815,Friedrichshain-Kreuzberg,11002002,Kreuzberg,0202,"9-12, Am Weinhang, Viktoria-Quartier, Kreuzber...",130659.398917

--- sbahn ---

,station_id,station,line,latitude,longitude,district,district_id
0,3,S+U Westhafen (Berlin),"{S41,S42,S46}",52.536217,13.344329,Mitte,11001001
1,4,S+U Westhafen (Berlin),"{S41,S42,S46}",52.536320,13.344298,Mitte,11001001
2,5,S Bellevue (Berlin),"{S3,S5,S7,S9}",52.519947,13.348090,Mitte,11001001
3,6,S Bellevue (Berlin),"{S3,S5,S7,S9}",52.520010,13.348101,Mitte,11001001
4,7,S Tiergarten (Berlin),"{S3,S5,S7,S9}",52.514420,13.336536,Mitte,11001001

--- kindergartens ---

,kindergarten_id,name,operator,capacity,address,latitude,longitude,district,district_id,neighborhood,neighborhood_id,full_address
0,137549003,Bunte Klänge Kindergarten,None,None,"Graf-Haeseler-Straße 23, 13403 Berlin",52.569958,13.313863,Reinickendorf,11012012,Reinickendorf,1201,"Bunte Klänge Kindergarten, 23, Graf-Haeseler-..."
1,167048488,Nestwärme Kita,None,None,None,52.501537,13.433399,Friedrichshain-Kreuzberg,11002002,Kreuzberg,202,"Nestwärme Kita, Wrangelstraße, Luisenstadt, Kr..."
2,268915158,Kita Fehlerstraße 2,None,None,"Fehlerstraße 2, 12161 Berlin",52.476740,13.325825,Tempelhof-Schöneberg,11007007,Friedenau,702,"Kita Fehlerstraße 2, 2, Fehlerstraße, Friedena..."
3,268915167,Ganztagsbetreuung der Fläming-Grundschule,Nachbarschaftsheim Schöneberg e.V.,None,"Rheinstraße 54, 12161 Berlin",52.468520,13.332504,Tempelhof-Schöneberg,11007007,Friedenau,702,"Ganztagsbetreuung der Fläming-Grundschule, 54,..."
4,268915173,kidsweb.de Kindertagesbetreuung,None,None,None,52.539883,13.349625,Mitte,11001001,Wedding,105,"kidsweb.de Kindertagesbetreuung, Fehmarner Str..."

--- ubahn ---

,station,line,latitude,longitude,postcode,neighborhood,district,district_id
0,Adenauerplatz,U7,52.499722,13.307222,10707,Charlottenburg,Charlottenburg-Wilmersdorf,11004004
1,Afrikanische Straße,U6,52.560028,13.334633,13349,Wedding,Mitte,11001001
2,Alexanderplatz,U5,52.521389,13.411944,10178,Mitte,Mitte,11001001
3,Alexanderplatz,U2,52.521389,13.411944,10178,Mitte,Mitte,11001001
4,Alexanderplatz,U8,52.521389,13.411944,10178,Mitte,Mitte,11001001

--- playgrounds ---

,playground_id,name,latitude,longitude,district,district_id,neighborhood,neighborhood_id,area_sq_m,full_address
0,4675776,Unknown,52.533085,13.346343,Mitte,11001001,Moabit,0102,4247.857798,"Stephanstraße, Stephankiez, Moabit, Mitte, Ber..."
1,4675787,Unknown,52.534153,13.344207,Mitte,11001001,Moabit,0102,1488.792935,"Salzwedeler Straße, Stephankiez, Moabit, Mitte..."
2,4687127,Unknown,52.525066,13.473750,Lichtenberg,11011011,Fennpfuhl,1111,222.216294,"Paul-Junius-Straße, Fennpfuhl, Lichtenberg, Be..."
3,4703528,Unknown,52.533222,13.337152,Mitte,11001001,Moabit,0102,214.382142,"Unionstraße, Stephankiez, Moabit, Mitte, Berli..."
4,4707958,Spielplatz Zwinglistraße,52.525870,13.329238,Mitte,11001001,Moabit,0102,685.914246,"Spielplatz Zwinglistraße, 18, Zwinglistraße, B..."

--- exhibition_centers ---

,id,exhibition_center_name,house_number,street,neighborhood_id,district_id,postal_code,website,building,wikipedia,latitude,longitude
0,136079469,messe berlin,None,alemannen allee,0405,11004004,14052,https://www.messe-berlin.de/,None,de:messegelände (berlin),52.503449,13.272199
1,196694606,citycube berlin,26,messe damm,0405,11004004,14055,http://www.citycube-berlin.de/,yes,de:citycube berlin,52.500120,13.270794
2,680746621,hub27,None,jaffé straße,0405,11004004,14055,https://www.messe-berlin.de/de/veranstalter/un...,yes,None,52.502896,13.267529
3,719414532,ausstellungspavillon,None,None,1001,11010010,None,None,yes,None,52.539210,13.570826

### Check tables for certain columns

In [8]:
# Get columns with 'id', 'name', 'lat', 'lon' in their names
query = """
  WITH tables AS (
      SELECT table_name
      FROM information_schema.tables
      WHERE table_schema = 'berlin_source_data'
        AND table_type = 'BASE TABLE'
        AND table_name NOT ILIKE '%test%' AND table_name NOT ILIKE '%stat%'
  ),
  cols AS (
      SELECT table_name, column_name
      FROM information_schema.columns
      WHERE table_schema = 'berlin_source_data'
  )
  SELECT t.table_name,
        -- check for each required pattern
        bool_or(c.column_name ILIKE '%id%' AND c.column_name != 'district_id') AS has_id,
        bool_or(c.column_name ILIKE '%name%' OR c.column_name ILIKE '%station%' OR c.column_name ILIKE '%district%' ) AS has_name,
        bool_or(c.column_name ='district_id') AS has_district_id,
        bool_or(c.column_name ILIKE '%hood_id%') AS has_neighborhood_id,
        bool_or(c.column_name ILIKE '%lat%')  AS has_lat,
        bool_or(c.column_name ILIKE '%lon%')  AS has_lon,
        bool_or(c.column_name ILIKE '%geom%')  AS has_geom
  FROM tables t
  LEFT JOIN cols c ON t.table_name = c.table_name
  GROUP BY t.table_name
  ORDER BY t.table_name;
"""
# Execute the query
with engine.connect() as conn:
    df= pd.read_sql(text(query), conn)
    conn.commit()  # commit the transaction
df

,table_name,has_id,has_name,has_district_id,has_neighborhood_id,has_lat,has_lon,has_geom
0,banks,True,True,True,False,True,True,False
1,bike_lanes,True,True,True,True,False,False,True
2,bus_tram_stops,True,True,True,False,True,True,False
3,dental_offices,True,True,True,False,True,True,False
4,district_level_aggregated,True,True,True,False,True,True,False
5,districts,False,True,True,False,False,False,True
6,doctors,True,True,True,True,True,True,False
7,exhibition_centers,True,True,True,True,True,True,False
8,galleries,True,True,True,True,True,True,False
9,gyms,True,True,True,False,True,True,True
10,hospitals,False,True,True,False,True,True,False
11,hospitals_refactored,True,True,True,False,True,True,True
12,kindergartens,True,True,True,True,True,True,False
13,land_prices,False,True,True,False,False,False,False
14,long_term_listings,True,True,True,False,True,True,True
15,malls,True,True,True,True,True,True,False
16,milieuschutz_protection_zones,True,True,True,False,False,False,True
17,museums,True,True,True,True,True,True,False
18,neighborhoods,True,True,True,True,False,False,True
19,night_clubs,True,True,True,True,True,True,False
20,parks,True,True,True,True,True,True,False
21,pharmacies,True,True,True,False,True,True,False
22,playgrounds,True,True,True,True,True,True,False
23,pools,True,True,True,False,True,True,False
24,pools_refactored,True,True,True,True,True,True,False
25,post_offices,True,True,True,True,True,True,False
26,public_artworks,True,True,True,True,True,True,False
27,sbahn,True,True,True,False,True,True,False
28,schools,True,True,True,False,True,True,False
29,short_term_listings,True,True,True,False,True,True,False
30,social_clubs_activities,True,True,True,True,True,True,True
31,supermarkets,True,True,True,True,True,True,False
32,theaters,True,True,True,True,True,True,False
33,theaters_backup_neigh_final,True,True,True,True,True,True,False
34,ubahn,False,True,True,False,True,True,False
35,universities,True,True,True,False,True,True,False
36,venues,True,True,True,False,True,True,False
37,veterinary_clinics,True,True,True,True,False,False,True
38,veterinary_clinics_martin_svitek,True,True,True,True,True,True,False

### Create a standard table for POI

In [84]:
from sqlalchemy import text

query = """

DROP TABLE IF EXISTS point_of_interest CASCADE;

CREATE TABLE point_of_interest (
    poi_id TEXT PRIMARY KEY,
    name TEXT,
    layer TEXT, -- 'galleries' or 'museums'
    district_id TEXT,
    district TEXT,
    neighborhood_id TEXT,
    neighborhood TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    geometry geometry(Point, 4326),
    attributes JSONB
);
"""

# Execute the DDL
with engine.begin() as conn:   # begin() handles commit automatically
    conn.execute(text(query))

### Insert rows into the POI - needs to be automated and poi_id to use the table name and not the actual word inserted, same for the layer column

In [85]:
insert_query = """
INSERT INTO point_of_interest (poi_id, name, layer, district_id, district, neighborhood_id, neighborhood,
                 latitude, longitude, geometry, attributes)
SELECT
    CONCAT(SUBSTRING('galleries' FROM 1 FOR 3), '-', g.id) AS poi_id,
    g.name,
    'galleries' AS layer,
    g.district_id,
    d.district AS district,
    g.neighborhood_id,
    n.neighborhood AS neighborhood,
    g.latitude,
    g.longitude,
    ST_SetSRID(ST_MakePoint(g.longitude, g.latitude), 4326) AS geometry,
    to_jsonb(g) - 'id' - 'name' - 'district_id' - 'neighborhood_id'
                 - 'latitude' - 'longitude' - 'geometry' AS attributes
FROM berlin_source_data.galleries g
JOIN berlin_source_data.districts d ON g.district_id = d.district_id
JOIN berlin_source_data.neighborhoods n ON g.neighborhood_id = n.neighborhood_id

UNION ALL

SELECT
    CONCAT(SUBSTRING('museums' FROM 1 FOR 3), '-', m.id) AS poi_id,
    m.name,
    'museums' AS layer,
    m.district_id,
    d.district AS district,
    m.neighborhood_id,
    n.neighborhood AS neighborhood,
    m.latitude,
    m.longitude,
    ST_SetSRID(ST_MakePoint(m.longitude, m.latitude), 4326) AS geometry,
    to_jsonb(m) - 'id' - 'name' - 'district_id' - 'neighborhood_id'
                 - 'latitude' - 'longitude' - 'geometry' AS attributes
FROM berlin_source_data.museums m
JOIN berlin_source_data.districts d ON m.district_id = d.district_id
JOIN berlin_source_data.neighborhoods n ON m.neighborhood_id = n.neighborhood_id

UNION ALL

SELECT
    CONCAT(SUBSTRING('listings' FROM 1 FOR 3), '-', l.listing_id) AS poi_id,
    l.detail_url as name,
    'listings' AS layer,
    l.district_id,
    d.district AS district,
    n.neighborhood_id,
    l.neighborhood AS neighborhood,
    l.latitude,
    l.longitude,
    ST_SetSRID(ST_MakePoint(l.longitude, l.latitude), 4326) AS geometry,
    to_jsonb(l) - 'id' - 'detail_url' - 'district_id' - 'neighborhood'
                 - 'latitude' - 'longitude' - 'geometry' AS attributes
FROM berlin_source_data.long_term_listings l
JOIN berlin_source_data.districts d ON l.district_id = d.district_id
JOIN berlin_source_data.neighborhoods n ON l.neighborhood = n.neighborhood

UNION ALL

SELECT
    CONCAT(SUBSTRING('banks' FROM 1 FOR 3), '-', b.bank_id) AS poi_id,
    b.name as name,
    'banks' AS layer,
    b.district_id,
    d.district AS district,
    '0000' AS neighborhood_id,
    'Unknown' AS  neighborhood,
    b.latitude,
    b.longitude,
    ST_SetSRID(ST_MakePoint(b.longitude, b.latitude), 4326) AS geometry,
    to_jsonb(b) - 'id' - 'detail_url' - 'district_id' - 'neighborhood'
                 - 'latitude' - 'longitude' - 'geometry' AS attributes
FROM berlin_source_data.banks b
JOIN berlin_source_data.districts d ON b.district_id = d.district_id
;
"""

with engine.begin() as conn:
    conn.execute(text(insert_query))

### Show 20 rows of POI table

In [66]:
query = f"""
SELECT poi_id,
    name,
    layer,
    district_id,
    district,
    neighborhood_id,
    neighborhood,
    latitude,
    longitude,
     ST_AsText(geometry) AS geom_wkt,
    attributes
FROM point_of_interest 
WHERE district = 'Spandau'
LIMIT 20;
"""

# Execute the query
with engine.connect() as conn:
    df= pd.read_sql(text(query), conn)
    conn.commit()  # commit the transaction
df

,poi_id,name,layer,district_id,district,neighborhood_id,neighborhood,latitude,longitude,geom_wkt,attributes
0,gal-10111146177,galerie im alten zollhaus,galleries,11005005,Spandau,0504,Staaken,52.522984,13.147897,POINT(13.147897 52.522984),"{'fee': None, 'street': 'heer straße', 'websit..."
1,gal-12734386032,kommunale galerie im historischen keller,galleries,11005005,Spandau,0501,Spandau,52.538544,13.204411,POINT(13.204411 52.538544),"{'fee': 'false', 'street': 'reformations platz..."
2,gal-26121688,kunstremise spandau,galleries,11005005,Spandau,0501,Spandau,52.537120,13.201191,POINT(13.201191 52.53712),"{'fee': None, 'street': 'viktoria ufer', 'webs..."
3,mus-344381412,enthüllt. berlin und seine denkmäler,museums,11005005,Spandau,0502,Haselhorst,52.541218,13.213854,POINT(13.213854 52.541218),"{'fee': 'true', 'street': 'am juliusturm', 'we..."
4,mus-2335146075,das gotische haus,museums,11005005,Spandau,0501,Spandau,52.537686,13.206724,POINT(13.206724 52.537686),"{'fee': None, 'street': None, 'website': 'http..."
5,mus-2853421751,spandovia sacra – museum mit bibliothek und ar...,museums,11005005,Spandau,0501,Spandau,52.538780,13.205653,POINT(13.205653 52.53878),"{'fee': None, 'street': None, 'website': None,..."
6,mus-3977880885,gutshof gatow,museums,11005005,Spandau,0505,Gatow,52.484940,13.181724,POINT(13.181724 52.48494),"{'fee': None, 'street': 'buchwald ziele', 'web..."
7,mus-8428338215,militär-historisches museum berlin-gatow,museums,11005005,Spandau,0506,Kladow,52.471926,13.138677,POINT(13.138677 52.471926),"{'fee': None, 'street': 'am flugplatz gatow', ..."
8,mus-25775881,stadtgeschichtliches museum spandau,museums,11005005,Spandau,0502,Haselhorst,52.540634,13.213536,POINT(13.213536 52.540634),"{'fee': 'true', 'street': None, 'website': Non..."
9,lis-WOH_759_42_13599,https://www.immowelt.de/expose/29290c8b-1ceb-4...,listings,11005005,Spandau,0502,Haselhorst,52.555490,13.224585,POINT(13.2245846 52.5554901),"{'city': 'Berlin', 'type': 'Wohnung', 'floor':..."
10,lis-WOH_1010_56_13599,https://www.immowelt.de/expose/b00e0107-e4c1-4...,listings,11005005,Spandau,0502,Haselhorst,52.556522,13.224688,POINT(13.2246878 52.5565218),"{'city': 'Berlin', 'type': 'Wohnung', 'floor':..."
11,lis-WOH_1013_59_13599,https://www.immowelt.de/expose/e81d0e0b-5e1a-4...,listings,11005005,Spandau,0502,Haselhorst,52.558891,13.226792,POINT(13.2267919 52.5588912),"{'city': 'Berlin', 'type': 'Wohnung', 'floor':..."
12,lis-WOH_973_48_13599,https://www.immowelt.de/expose/704da7fe-d6f9-4...,listings,11005005,Spandau,0502,Haselhorst,52.554735,13.227497,POINT(13.227497 52.554735),"{'city': 'Berlin', 'type': 'Wohnung', 'floor':..."
13,lis-WOH_940_81_13587,https://www.immowelt.de/expose/0cf7830f-74c2-4...,listings,11005005,Spandau,0507,Hakenfelde,52.559030,13.218500,POINT(13.2184997 52.5590296),"{'city': 'Berlin', 'type': 'Wohnung', 'floor':..."
14,lis-WOH_521_53_13599,https://www.immowelt.de/expose/37f3a422-456a-4...,listings,11005005,Spandau,0502,Haselhorst,52.539753,13.238031,POINT(13.238031 52.5397531),"{'city': 'Berlin', 'type': 'Wohnung', 'floor':..."
15,lis-WOH_756_48_13581,https://www.immowelt.de/expose/f2e98f40-c3c2-4...,listings,11005005,Spandau,0501,Spandau,52.530229,13.194736,POINT(13.1947355 52.5302293),"{'city': 'Berlin', 'type': 'Wohnung', 'floor':..."
16,lis-WOH_1599_75_13587,https://www.immowelt.de/expose/65bafbb7-7533-4...,listings,11005005,Spandau,0507,Hakenfelde,52.555596,13.209328,POINT(13.2093283 52.5555957),"{'city': 'Berlin', 'type': 'Wohnung', 'floor':..."
17,lis-WOH_1050_50_13595,https://www.immowelt.de/expose/25xg4xmnp689?ln...,listings,11005005,Spandau,0509,Wilhelmstadt,52.524624,13.195118,POINT(13.1951184 52.5246244),"{'city': 'Berlin', 'type': 'Wohnung', 'floor':..."
18,lis-WOH_1600_97_14089,https://www.immowelt.de/expose/254t32raxzy6?ln...,listings,11005005,Spandau,0506,Kladow,52.472197,13.123399,POINT(13.1233985 52.4721969),"{'city': 'Berlin', 'type': 'Wohnung', 'floor':..."
19,lis-STU_399_53_13585,https://www.immowelt.de/expose/cafa26c2-15c7-4...,listings,11005005,Spandau,0501,Spandau,52.552307,13.197099,POINT(13.1970986 52.5523071),"{'city': 'Berlin', 'type': 'Studio', 'floor': ..."

### Show some attributes of row 5 to see what it looks like

In [56]:
query = f"""
SELECT attributes
FROM point_of_interest 

LIMIT 20;
"""

# Execute the query
with engine.connect() as conn:
    df= pd.read_sql(text(query), conn)
    conn.commit()  # commit the transaction
df
print(json.dumps(df.loc[5, "attributes"], indent=2))

{
  "fee": "false",
  "street": "schierker stra\u00dfe",
  "website": null,
  "wheelchair": "yes",
  "postal_code": "12051",
  "house_number": "35",
  "opening_hours": "tu-th 11:00-22:00; fr,sa 11:00-23:00"
}

### ⚡ Indexing for Speed - GiST index on the geometry column

In [86]:
query = """
CREATE INDEX idx_poi_geom
ON point_of_interest
USING GIST (geometry);
"""

with engine.connect() as conn:
    conn.execute(text(query))   # run the CREATE INDEX
    conn.commit()               # commit the transaction

In [58]:
check_query = """
SELECT indexname, indexdef
FROM pg_indexes
WHERE tablename = 'point_of_interest';
"""
with engine.connect() as conn:
    testdf= pd.read_sql(text(check_query), conn)
    conn.commit()  # commit the transaction

testdf

                indexname                                           indexdef
0  point_of_interest_pkey  CREATE UNIQUE INDEX point_of_interest_pkey ON ...
1            idx_poi_geom  CREATE INDEX idx_poi_geom ON public.point_of_i...

### Look at long_term_listings table and hospitals bank table

In [59]:
query = """
SELECT *
FROM berlin_source_data.long_term_listings
LIMIT 2;
"""
# Execute the query
df = pd.read_sql(text(query), engine)
df

,listing_id,detail_url,raw_info,type,first_tenant,price_euro,number_of_rooms,surface_m2,floor,street,house_number,neighborhood,district,postal_code,city,address,latitude,longitude,geometry,district_id
0,WOH_2772_178_14055,https://www.immowelt.de/expose/fb32adca-5d67-4...,Wohnung zur Miete 2.772 € 4 Zimmer 178 m² frei...,Wohnung,no,2772,4.0,178.0,None,Stallupöner Allee,33,Westend,Charlottenburg-Wilmersdorf,14055,Berlin,Stallupöner Allee 33 14055 Westend Berlin,52.504417,13.234717,POINT (13.234717 52.504417),11004004
1,STU_495_43_13627,https://www.immowelt.de/expose/4985f014-94b9-4...,"Studio zur Miete 495 € 2 Zimmer 43,7 m² frei a...",Studio,no,495,2.0,43.7,None,Schweiggerweg,5,Charlottenburg-Nord,Charlottenburg-Wilmersdorf,13627,Berlin,Schweiggerweg 5 13627 Charlottenburg Berlin,52.538645,13.282277,POINT (13.2822767 52.5386453),11004004

In [60]:
query = """
SELECT *
FROM berlin_source_data.banks
LIMIT 2;
"""
# Execute the query
df = pd.read_sql(text(query), engine)
df

,bank_id,name,brand,operator,street,housenumber,postcode,opening_hours,atm,wheelchair,latitude,longitude,district,district_id
0,28968292,berliner volksbank,berliner volksbank,nan,berliner straße,42,10713,"mo-fr 10:00-13:00, mo 14:00-16:00, tu,th 14:00...",true,true,52.486668,13.319723,Charlottenburg-Wilmersdorf,11004004
1,60848455,sparkasse,nan,berliner sparkasse,anton-saefkow-platz,13,10369,"mo,we,fr 09:30-15:00; tu,th 09:30-18:00",true,unknown,52.530331,13.471037,Lichtenberg,11011011

### Show closest hospital to each listing

In [61]:
query = """
    SELECT l.listing_id,
        h.hospital_id AS hospital_id,
        h.name AS hospital_name,
        ST_DistanceSphere(ST_GeomFromText(l.geometry, 4326), ST_GeomFromText(h.geometry, 4326)) AS distance_meters
    FROM berlin_source_data.long_term_listings l
    JOIN LATERAL (
        SELECT hospital_id, name, geometry
        FROM berlin_source_data.hospitals_refactored h
        ORDER BY ST_GeomFromText(l.geometry, 4326) <-> ST_GeomFromText(h.geometry, 4326)   -- efficient nearest-neighbor using GiST index
        LIMIT 1
    ) h ON true;
"""
# Execute the query
df = pd.read_sql(text(query), engine)
df

,listing_id,hospital_id,hospital_name,distance_meters
0,WOH_2772_178_14055,138215763,Paulinen Krankenhaus,385.444188
1,STU_495_43_13627,114201147,Schlosspark-Klinik,1882.795097
2,STU_1625_44_10717,23484458,Ärztehaus am Hohenzollerndamm,234.123495
3,WOH_2400_132_14050,12218907397,Fertility Center Berlin,466.746290
4,WOH_1200_45_10589,114201147,Schlosspark-Klinik,745.140126
...,...,...,...,...
1162,HAU_2350_169_12587,5037228530,Ärzte Zentrum am Markt,931.006981
1163,STU_2500_169_12587,5037228530,Ärzte Zentrum am Markt,931.006981
1164,WOH_2398_109_12527,69869582,Krankenhaus Hedwigshöhe,4646.899357
1165,WOH_1840_76_14059,9178079418,Ärztehaus,644.476418
1166,WOH_855_45_12619,69869582,Krankenhaus Hedwigshöhe,17190.904196

In [ ]:
query = """

"""
# Execute the query
df = pd.read_sql(text(query), engine)
df

### Create the json column to show nearest neighbor - can be automated so dont need to create a layer section each time

In [88]:
query = """
    ALTER TABLE point_of_interest  ADD COLUMN nearest_pois jsonb;

    UPDATE point_of_interest l
    SET nearest_pois = jsonb_build_object(
        'gallery', (
            SELECT jsonb_build_object(
                'id', h.poi_id, 
                'name', h.name, 
                'distance', ST_DistanceSphere(l.geometry, h.geometry),
                'address', jsonb_build_object('street', h.attributes->>'street', 'house_number', h.attributes->>'house_number'))
            FROM point_of_interest h
            WHERE h.layer = 'galleries'
            ORDER BY l.geometry <-> h.geometry
            LIMIT 1
        ),
        'museum', (
            SELECT jsonb_build_object(
                'id', m.poi_id, 
                'name', m.name, 
                'distance', ST_DistanceSphere(l.geometry, m.geometry),
                'address', jsonb_build_object('street', m.attributes->>'street', 'house_number', m.attributes->>'house_number'))
            FROM point_of_interest m
            WHERE m.layer = 'museums'
            ORDER BY l.geometry <-> m.geometry
            LIMIT 1
        ),
        'bank', (
            SELECT jsonb_build_object(
                'id', b.poi_id, 
                'name', b.name, 
                'distance', ST_DistanceSphere(l.geometry, b.geometry),
                'address', jsonb_build_object('street', b.attributes->>'street', 'house_number', b.attributes->>'house_number'))
            FROM point_of_interest b
            WHERE b.layer = 'banks'
            ORDER BY l.geometry <-> b.geometry
            LIMIT 1
        )
    )
    WHERE l.layer = 'listings';
"""
# Execute the query
with engine.begin() as conn:
    conn.execute(text(query))

### Run query to show 10 listings

In [89]:
query = f"""
SELECT *
FROM point_of_interest 
WHERE layer = 'listings'
LIMIT 10;
"""

# Execute the query
with engine.connect() as conn:
    df= pd.read_sql(text(query), conn)
    conn.commit()  # commit the transaction
df

,poi_id,name,layer,district_id,district,neighborhood_id,neighborhood,latitude,longitude,geometry,attributes,nearest_pois
0,lis-WOH_2772_178_14055,https://www.immowelt.de/expose/fb32adca-5d67-4...,listings,11004004,Charlottenburg-Wilmersdorf,0405,Westend,52.504417,13.234717,0101000020E610000066A19DD32C782A40F1457BBC9040...,"{'city': 'Berlin', 'type': 'Wohnung', 'floor':...","{'bank': {'id': 'ban-671776291', 'name': 'bank..."
1,lis-STU_495_43_13627,https://www.immowelt.de/expose/4985f014-94b9-4...,listings,11004004,Charlottenburg-Wilmersdorf,0406,Charlottenburg-Nord,52.538645,13.282277,0101000020E61000007AD8559286902A4072D24554F244...,"{'city': 'Berlin', 'type': 'Studio', 'floor': ...","{'bank': {'id': 'ban-437514581', 'name': 'spar..."
2,lis-STU_2716_80_14057,https://www.immowelt.de/expose/6a4f3322-2f3f-4...,listings,11004004,Charlottenburg-Wilmersdorf,0401,Charlottenburg,52.506960,13.286736,0101000020E6100000F52B9D0FCF922A4056325B0DE440...,"{'city': 'Berlin', 'type': 'Studio', 'floor': ...","{'bank': {'id': 'ban-1819283270', 'name': 'pos..."
3,lis-STU_1625_44_10717,https://www.immowelt.de/expose/2144d17c-ae55-4...,listings,11004004,Charlottenburg-Wilmersdorf,0402,Wilmersdorf,52.492051,13.320604,0101000020E610000052ED783826A42A4026BA7889FB3E...,"{'city': 'Berlin', 'type': 'Studio', 'floor': ...","{'bank': {'id': 'ban-2445456642', 'name': 'spa..."
4,lis-WOH_2400_132_14050,https://www.immowelt.de/expose/8d048a9f-4bf4-4...,listings,11004004,Charlottenburg-Wilmersdorf,0405,Westend,52.520175,13.269123,0101000020E61000004537B176CA892A4049DBF8139542...,"{'city': 'Berlin', 'type': 'Wohnung', 'floor':...","{'bank': {'id': 'ban-667211363', 'name': 'berl..."
5,lis-WOH_1200_45_10589,https://www.immowelt.de/expose/25ne5mmgni7e?ln...,listings,11004004,Charlottenburg-Wilmersdorf,0401,Charlottenburg,52.524411,13.300144,0101000020E61000006C335F6FAC992A402553AAE91F43...,"{'city': 'Berlin', 'type': 'Wohnung', 'floor':...","{'bank': {'id': 'ban-1915389761', 'name': 'spa..."
6,lis-WOH_1584_64_10719,https://www.immowelt.de/expose/1f6dafb1-fa25-4...,listings,11004004,Charlottenburg-Wilmersdorf,0402,Wilmersdorf,52.487919,13.323358,0101000020E610000022D04F278FA52A4000CC1022743E...,"{'city': 'Berlin', 'type': 'Wohnung', 'floor':...","{'bank': {'id': 'ban-2307254000', 'name': 'deu..."
7,lis-WOH_1850_83_10585,https://www.immowelt.de/expose/1a8a9d5a-9727-4...,listings,11004004,Charlottenburg-Wilmersdorf,0401,Charlottenburg,52.514088,13.304205,0101000020E6100000E59590B4C09B2A40382163A4CD41...,"{'city': 'Berlin', 'type': 'Wohnung', 'floor':...","{'bank': {'id': 'ban-416660137', 'name': 'targ..."
8,lis-WOH_1760_61_10777,https://www.immowelt.de/expose/529f581d-b85c-4...,listings,11004004,Charlottenburg-Wilmersdorf,0402,Wilmersdorf,52.497551,13.332489,0101000020E61000008E8DE5023CAA2A400B4DC8BDAF3F...,"{'city': 'Berlin', 'type': 'Wohnung', 'floor':...","{'bank': {'id': 'ban-35983986', 'name': 'inves..."
9,lis-STU_2580_85_10713,https://www.immowelt.de/expose/836ad724-e86d-4...,listings,11004004,Charlottenburg-Wilmersdorf,0402,Wilmersdorf,52.485510,13.318918,0101000020E6100000CF37FD3449A32A4017EF6C34253E...,"{'city': 'Berlin', 'type': 'Studio', 'floor': ...","{'bank': {'id': 'ban-28968292', 'name': 'berli..."

In [90]:
query = f"""
SELECT nearest_pois
FROM point_of_interest 
WHERE layer = 'listings';
"""

# Execute the query
with engine.connect() as conn:
    df= pd.read_sql(text(query), conn)
    conn.commit()  # commit the transaction
df
print(json.dumps(df.loc[5, "nearest_pois"], indent=2))

{
  "bank": {
    "id": "ban-1915389761",
    "name": "sparkasse",
    "address": {
      "street": "otto-suhr-allee",
      "house_number": null
    },
    "distance": 1011.56046421
  },
  "museum": {
    "id": "mus-9979815162",
    "name": "schloss charlottenburg",
    "address": {
      "street": "spandauer damm",
      "house_number": "10"
    },
    "distance": 485.49558849
  },
  "gallery": {
    "id": "gal-5265842119",
    "name": "galerie theis",
    "address": {
      "street": "schustehrus stra\u00dfe",
      "house_number": null
    },
    "distance": 840.65577041
  }
}

🧩 What’s Happening
For each listing row (WHERE l.category = 'listing'), Postgres runs three subqueries.

Each subquery filters the unified table by category (museum, gallery, bank).

The <-> operator finds the nearest neighbor using the GiST index on geom.

The results are bundled into a JSONB object and stored in nearest_pois.